const test=require('node:test'),assert=require('node:assert/strict');
const {generateKeyPairSync}=require('node:crypto');
const fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {Issuer,signedToken}=require('../licensing/issuer.cjs');
const {LicenceManager,verifyLicence}=require('../desktop/licence.cjs');
const {makeServer}=require('../licensing/server.cjs');
const {Store}=require('../desktop/store.cjs');const {Security}=require('../desktop/security.cjs');
const keys=generateKeyPairSync('ed25519'),device='a'.repeat(64),other='b'.repeat(64);
function fixture(t){let now=Date.now();const dir=fs.mkdtempSync(path.join(os.tmpdir(),'sole-license-'));const issuer=new Issuer({file:path.join(dir,'issuer.sqlite'),privateKey:keys.privateKey,now:()=>now});const manager=new LicenceManager({publicKey:keys.publicKey,file:path.join(dir,'licence.json'),deviceId:device,now:()=>now});t.after(()=>{issuer.close();fs.rmSync(dir,{recursive:true,force:true});});return{dir,issuer,manager,now:()=>now,advance:n=>now+=n,issue:(seats=1,offlineDays=7)=>issuer.issue({customer:'Test Factory',expiresAt:now+30*86400000,seats,offlineDays})};}
test('signed licence activates on its device and survives offline restart',t=>{const f=fixture(t),l=f.issue();const {token}=f.issuer.activate({code:l.activationCode,deviceId:device});f.manager.activate(token);assert.equal(f.manager.ensure().customer,'Test Factory');const restarted=new LicenceManager({publicKey:keys.publicKey,file:path.join(f.dir,'licence.json'),deviceId:device,now:f.now});assert.ok(restarted.ensure().active);assert.equal(f.issuer.list()[0].devices.length,1);f.issuer.activate({code:l.activationCode,deviceId:device});assert.equal(f.issuer.list()[0].devices.length,1);});
test('tampering, incorrect public key, wrong product and copied licence are rejected',t=>{const f=fixture(t),l=f.issue(),{token}=f.issuer.activate({code:l.activationCode,deviceId:device});assert.throws(()=>verifyLicence(token,keys.publicKey,other));assert.throws(()=>verifyLicence(token+'x',keys.publicKey,device));const c=JSON.parse(Buffer.from(token.split('.')[0],'base64url'));c.product='Other';assert.throws(()=>verifyLicence(signedToken(c,keys.privateKey),keys.publicKey,device));assert.throws(()=>verifyLicence(token,generateKeyPairSync('ed25519').publicKey,device));assert.throws(()=>f.manager.activate('IQ-LINKS-OWNER-2026'));});
test('seat limit is persistent, repeat activation is idempotent and revoked device cannot re-register',t=>{const f=fixture(t),l=f.issue();f.issuer.activate({code:l.activationCode,deviceId:device});assert.throws(()=>f.issuer.activate({code:l.activationCode,deviceId:other}),/limit/);const reopened=new Issuer({file:path.join(f.dir,'issuer.sqlite'),privateKey:keys.privateKey,now:f.now});try{assert.throws(()=>reopened.activate({code:l.activationCode,deviceId:other}),/limit/);}finally{reopened.close();}f.issuer.revoke({licenseId:l.licenseId,deviceId:device});f.issuer.activate({code:l.activationCode,deviceId:other});assert.throws(()=>f.issuer.activate({code:l.activationCode,deviceId:device}),/revoked/);});
test('offline refresh deadline and expiry block previously logged-in operations',t=>{const f=fixture(t),l=f.issue(1,1),{token}=f.issuer.activate({code:l.activationCode,deviceId:device});const st=new Store(':memory:'),s=new Security(st,f.now,f.manager);t.after(()=>st.close());s.run('activate',{key:token});s.run('setup-company',{companyName:'Factory',owner:'Owner'});s.run('create-user',{username:'owner',role:'owner',password:'Password123'});s.run('login',{username:'owner',password:'Password123'});f.advance(86400001);assert.equal(s.run('status').activated,false);assert.throws(()=>s.run('snapshot'),/Licence/);assert.throws(()=>s.run('login',{username:'owner',password:'Password123'}),/Licence/);assert.equal(st.all('user').length,1);const renewed=f.issuer.activate({code:l.activationCode,deviceId:device});s.run('activate',{key:renewed.token});assert.ok(s.run('status').activated);f.advance(31*86400000);assert.match(f.manager.status().reason,/expired/);});
test('clock rollback, corrupt files and malformed claims fail closed',t=>{const f=fixture(t),l=f.issue(),{token}=f.issuer.activate({code:l.activationCode,deviceId:device});f.manager.activate(token);f.advance(3600000);f.manager.ensure();f.advance(-3600000);assert.match(f.manager.status().reason,/backwards/);assert.throws(()=>f.manager.activate(token),/date/);fs.writeFileSync(path.join(f.dir,'licence.json'),'broken');assert.equal(f.manager.status().active,false);const c=JSON.parse(Buffer.from(token.split('.')[0],'base64url'));c.offlineUntil=c.expiresAt+1;assert.throws(()=>verifyLicence(signedToken(c,keys.privateKey),keys.publicKey,device));});
test('service authenticates administration and applies seat limits to concurrent requests',async t=>{const f=fixture(t),server=makeServer(f.issuer,'x'.repeat(40));await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>server.close(r)));const base='http://127.0.0.1:'+server.address().port;const post=(route,data,admin=false)=>fetch(base+route,{method:'POST',headers:{'Content-Type':'application/json',...(admin?{Authorization:'Bearer '+'x'.repeat(40)}:{})},body:JSON.stringify(data)});assert.equal((await post('/admin/issue',{})).status,401);const issued=await (await post('/admin/issue',{customer:'API Test',expiresAt:f.now()+86400000,seats:1,offlineDays:1},true)).json();const results=await Promise.all([device,other].map(deviceId=>post('/activate',{code:issued.activationCode,deviceId})));assert.deepEqual(results.map(r=>r.status).sort(),[200,400]);const response=results.find(r=>r.status===200);const body=await response.json();assert.ok(body.token);await post('/admin/revoke',{licenseId:issued.licenseId},true);assert.equal((await post('/activate',{code:issued.activationCode,deviceId:device})).status,400);});
